import os
os.chdir(f"/home/xlab-app-center")
os.system(f"git clone -b v2.5 https://github.com/camenduru/stable-diffusion-webui /home/xlab-app-center/stable-diffusion-webui")
os.chdir(f"/home/xlab-app-center/stable-diffusion-webui")
os.system(f"git clone https://github.com/etherealxx/batchlinks-webui /home/xlab-app-center/stable-diffusion-webui/extensions/batchlinks-webui")
os.system(f"git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui-nsfw-censor /home/xlab-app-center/stable-diffusion-webui/extensions/stable-diffusion-webui-nsfw-censor")
os.system(f"git lfs install")
os.system(f"git reset --hard")
os.system(f"sed -i -e '/demo:/r /home/xlab-app-center/header.py' /home/xlab-app-center/stable-diffusion-webui/modules/ui.py")
os.system(f"sed -i -e '253,258d' /home/xlab-app-center/stable-diffusion-webui/modules/ui_settings.py")
os.system(f"sed -i -e '186,228d' /home/xlab-app-center/stable-diffusion-webui/modules/ui_settings.py")
os.system(f"sed -i -e '171,178d' /home/xlab-app-center/stable-diffusion-webui/modules/ui_settings.py")
os.system(f"sed -i -e '108,113d' /home/xlab-app-center/stable-diffusion-webui/modules/ui_settings.py")
os.system(f"sed -i -e '208,210d' /home/xlab-app-center/stable-diffusion-webui/modules/ui_loadsave.py")
os.system(f"sed -i -e '197,200d' /home/xlab-app-center/stable-diffusion-webui/modules/ui_loadsave.py")
os.system(f"aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://civitai.com/api/download/models/130072 -d /home/xlab-app-center/stable-diffusion-webui/models/Stable-diffusion -o realisticVisionV51_v51VAE.safetensors")
os.system(f"aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://civitai.com/api/download/models/142219 -d /home/xlab-app-center/stable-diffusion-webui/models/Stable-diffusion -o x-men cyclops man 1a-000025.safetensors")
os.system(f"aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://civitai.com/api/download/models/128713 -d /home/xlab-app-center/stable-diffusion-webui/models/Stable-diffusion -o dreamshaper_8.safetensors")
os.system(f"aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://civitai.com/api/download/models/126470 -d /home/xlab-app-center/stable-diffusion-webui/models/Stable-diffusion -o majicmixRealistic_betterV2V25.safetensors")
os.system(f"aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://civitai.com/api/download/models/130072 -d /home/xlab-app-center/stable-diffusion-webui/models/Stable-diffusion -o realisticVisionV51_v51VAE.safetensors")
os.system(f"aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://civitai.com/api/download/models/142219 -d /home/xlab-app-center/stable-diffusion-webui/models/Stable-diffusion -o x-men cyclops man 1a-000025.safetensors")
os.system(f"aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://civitai.com/api/download/models/128713 -d /home/xlab-app-center/stable-diffusion-webui/models/Stable-diffusion -o dreamshaper_8.safetensors")
os.system(f"aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://civitai.com/api/download/models/126470 -d /home/xlab-app-center/stable-diffusion-webui/models/Stable-diffusion -o majicmixRealistic_betterV2V25.safetensors")
os.system(f"aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://civitai.com/api/download/models/46846 -d /home/xlab-app-center/stable-diffusion-webui/models/Stable-diffusion -o revAnimated_v122.safetensors")
os.system(f"aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://civitai.com/api/download/models/144566 -d /home/xlab-app-center/stable-diffusion-webui/models/Stable-diffusion -o samaritan3dCartoon_v40SDXL.safetensors")
os.system(f"aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://civitai.com/api/download/models/126688 -d /home/xlab-app-center/stable-diffusion-webui/models/Stable-diffusion -o dreamshaperXL10_alpha2Xl10.safetensors")
os.system(f"aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://civitai.com/api/download/models/136754 -d /home/xlab-app-center/stable-diffusion-webui/models/Stable-diffusion -o duchaitenAiartSDXL_v10.safetensors")
os.system(f"aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://civitai.com/api/download/models/132741 -d /home/xlab-app-center/stable-diffusion-webui/models/Stable-diffusion -o realcartoon3d_v6.safetensors")
os.system(f"aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://civitai.com/api/download/models/144229 -d /home/xlab-app-center/stable-diffusion-webui/models/Stable-diffusion -o protovisionXLHighFidelity3D_beta0520Bakedvae.safetensors")
os.system(f"aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://civitai.com/api/download/models/125771 -d /home/xlab-app-center/stable-diffusion-webui/models/Stable-diffusion -o toonyou_beta6.safetensors")
os.system(f"python launch.py --cors-allow-origins=* --xformers --enable-insecure-extension-access --theme dark --gradio-queue --disable-safe-unpickle --ui-settings-file /home/xlab-app-center/config.json --ui-config-file /home/xlab-app-center/ui-config.json")
